apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    app: mongodb
    tier: db
    project: roboshop
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
      tier: db
      project: roboshop
  template: # from here onwards pod definition starts
    metadata:
      namespace: roboshop
      labels:
        app: mongodb
        tier: db
        project: roboshop
    spec:
      containers:
      - name: mongodb
        image: shaiksuhail2767/mongodb:1.0.0
---
  apiVersion: v1
  kind: Service
  metadata:
    name: mongodb
    namespace: roboshop
  spec:
    selector:
      app: mongodb
      tier: db
      project: roboshop
    ports:
    - name: mongodb-port
      protocol: TCP
      port: 27017 #service port
      targetPort: 27017