apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    app: catalogue
    tier: app
    project: roboshop
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels:
      app: catalogue
      tier: app
      project: roboshop
  template: # from here onwards pod definition starts
    metadata:
      namespace: roboshop
      labels:
        app: catalogue
        tier: app
        project: roboshop
    spec:
      containers:
      - name: catalogue
        image: shaiksuhail2767/catalogue:1.0.0
        resources:
          requests:
            cpu: "50m"
            memory: "68Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"
        envFrom:
        - configMapRef:
            name: catalogue

---
  apiVersion: v1
  kind: Service
  metadata:
    name: catalogue
    namespace: roboshop
  spec:
    selector:
      app: catalogue
      tier: app
      project: roboshop
    ports:
    - name: catalogue-port
      protocol: TCP
      port: 8080 #service port
      targetPort: 8080
---
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: catalogue
    namespace: roboshop
  data:
    MONGO: "true"
    MONGO_URL: "mongodb://mongodb:27017/catalogue"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: catalogue
  namespace: roboshop
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: catalogue
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75

