apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: roboshop
  labels:
    app: user
    tier: app
    project: roboshop
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels:
      app: user
      tier: app
      project: roboshop
  template: # from here onwards pod definition starts
    metadata:
      namespace: roboshop
      labels:
        app: user
        tier: app
        project: roboshop
    spec:
      containers:
      - name: user
        image: shaiksuhail2767/user:1.0.0
        envFrom:
        - configMapRef:
            name: user

---
  apiVersion: v1
  kind: Service
  metadata:
    name: user
    namespace: roboshop
  spec:
    selector:
      app: user
      tier: app
      project: roboshop
    ports:
    - name: user-port
      protocol: TCP
      port: 8080 #service port
      targetPort: 8080
---
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: user
    namespace: roboshop
  data:
    MONGO: "true"
    MONGO_URL: "mongodb://mongodb:27017/user"
    REDIS_HOST: "redis"
